version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: forecast-web
    volumes:
      - ./:/backend
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - ENV = dev
    networks:
      - forecast-network
    depends_on:
      - db

  db:
    image: mysql:8.0.20
    container_name: forecast-db
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: forecast-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - forecast-network
    ports:
      - "3307:3306"

volumes:
  db_volume:

networks:
  forecast-network:
    driver: bridge