"""empty message

Revision ID: c134ab541022
Revises: 
Create Date: 2023-12-09 05:49:47.790675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c134ab541022'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('livedoor_area_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.create_table('m_telops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_m_telops_id'), 'm_telops', ['id'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('telop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['telop_id'], ['m_telops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_area_id'), 'forecasts', ['area_id'], unique=False)
    op.create_index(op.f('ix_forecasts_date'), 'forecasts', ['date'], unique=False)
    op.create_index(op.f('ix_forecasts_id'), 'forecasts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecasts_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_date'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_area_id'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_m_telops_id'), table_name='m_telops')
    op.drop_table('m_telops')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
